# Generated by Django 3.1.7 on 2021-05-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(choices=[('Vegan', 'vegan'), ('Vegetarian', 'vegetarian'), ('Gluten Free', 'glutenfree'), ('Diary Free', 'diaryfree'), ('Nut Free', 'nutfree')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, max_length=3, null=True)),
                ('weight', models.IntegerField(blank=True, max_length=3, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True)),
                ('height', models.IntegerField(blank=True, max_length=3, null=True)),
                ('diet', models.ManyToManyField(blank=True, to='Foods.SpecialDiet')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.FloatField(blank=True, max_length=9, null=True)),
                ('calories', models.IntegerField(blank=True, max_length=3, null=True)),
                ('fat', models.IntegerField(blank=True, max_length=3, null=True)),
                ('sodium', models.IntegerField(blank=True, max_length=3, null=True)),
                ('protein', models.IntegerField(blank=True, max_length=3, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('diet', models.ManyToManyField(blank=True, to='Foods.SpecialDiet')),
            ],
        ),
    ]
