# Generated by Django 3.1.7 on 2021-05-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdiet',
            name='diet',
            field=models.CharField(choices=[('Vegan', 'vegan'), ('Vegetarian', 'vegetarian'), ('wheat/gluten-free', 'wheat/gluten-free'), ('Diary Free', 'diary free'), ('Nut', 'nut'), ('Seafood', 'seafood')], max_length=20),
        ),
    ]
