# Generated by Django 3.1.7 on 2021-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0004_auto_20210524_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdiet',
            name='diet',
            field=models.CharField(choices=[('vegan', 'vegan'), ('vegetarian', 'vegetarian'), ('wheat/gluten-free', 'wheat/gluten-free'), ('diary free', 'diary free'), ('nut', 'nut'), ('seafood', 'seafood')], max_length=20, null=True),
        ),
    ]
