# Generated by Django 3.1.7 on 2021-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0005_auto_20210524_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdiet',
            name='diet',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
