# Generated by Django 3.1.7 on 2021-05-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0006_auto_20210524_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
