# Generated by Django 3.1.7 on 2021-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0008_auto_20210528_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to='tmp/images/'),
        ),
    ]
