# Generated by Django 3.1.7 on 2021-05-29 00:45

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0009_auto_20210528_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='foodyrmitstorage')),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='foodyrmitstorage')),
        ),
    ]
