# Generated by Django 3.1.7 on 2021-05-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0011_auto_20210529_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
