# Generated by Django 3.1.7 on 2021-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0012_remove_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
